name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, label-2] # Use the self-hosted runner with label 'label-1'

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      # Test Stage
      - name: Run Tests
        run: |
          echo "Testing application..."

      # Deploy Stage
      - name: Deploy Application
        run: |
          echo "Deploying application..."
